name: Function Action
description: (re)deploy a Cognite Function with schedules
inputs:
  function_name:
    description: Name of function. Used as an external_id for created function. Should be unique within cdf project.
    required: true
  function_folder:
    description: Path to the folder where source code for the function(s) is/are located.
    required: true
  cdf_deployment_credentials:
    description: CDF API key that is provided to the deployed function.
    required: true
  cdf_runtime_credentials:
    description: CDF API key that will be used when function is running.
    required: true
  cdf_project:
    description: The name of your cdf project. Will be checked that it matches required credentials.
    required: false
    default: ""
  cdf_base_url:
    description: Base url of your cdf project.
    default: https://api.cognitedata.com
    required: false
  function_file:
    description: Name of function file inside function folder, for instance, handler.py.
    default: handler.py
    required: false
  function_secrets:
    description: Base64 encoded string with json payload. Will be passed to a function's secrets as is.
    required: false
  schedule_file:
    description: |
        Relative path and name from (function_folder) of the file with schedules to be attached.
        Not passing this parameter, or passing "" (empty), no schedules will be attached.
        Note: On all deployments, all existing schedules are deleted (and possibly recreated)!
    required: false
    default: ""
  remove_only:
    description: Remove all artifacts and do not create new ones.
    default: false
    required: false
  overwrite:
    description: Overwrite the function if there is one with the same name.
    default: false
    required: false
outputs:
  function_external_id: # id of output
    description: The External ID of the function output. Use this to do calls against the API!
runs:
  using: docker
  image: Dockerfile
